// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/products/:handle" | "/contact";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/products._index.tsx": {
    id: "routes/products._index";
    page: "/products";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/products._index": typeof import("./app/routes/products._index.tsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
};